/**
 * This file is generated by the auto-version task. Modifying it will have no effect.
 */
package com.github.retrooper.packetevents.util;

import java.time.Instant;

public final class PEVersions {

    public static final String RAW = "2.10.1";
    public static final Instant BUILD_TIMESTAMP = Instant.ofEpochMilli(1762274601979L);
    public static final PEVersion CURRENT = new PEVersion(2, 10, 1, null);
    public static final PEVersion UNKNOWN = new PEVersion(0, 0, 0);
    
    private PEVersions() {
        throw new IllegalStateException();
    }
}